### ISSUE TITLE
no main in bower.json

### ISSUE THREAD

**Issue by rafriki** [panpeter/sb-admin-2#3]
Please fix as follows:

{
  "name": "sb-admin-2",
  "version": "0.0.1",
  "homepage": "https://github.com/panpeter/sb-admin-2",
  "authors": [
    "Piotr Wilczek"
  ],
  "description": "SB Admin 2 Bootstrap template",
  "main": [
    "js/sb-admin-2.js",
    "css/sb-admin-2.css"
  ],
  "license": "MIT",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "tests"
  ]
}

**Comment by panpeter** [comment]
rafriki I've added you as collaborator. Please feel free to update as necessary.
